const language = {
    title: { fin: 'Vaalikone', eng: 'VotingAid' },
    homePageDescription: { fin: 'Tervetuloa käyttämään vaalikonetta!', eng: 'Welcome to our voting aid application!' },
    selectStudentAssociation: { fin: 'Valitse opiskelijakuntasi', eng: 'Choose your student association' },
    navigationHome: { fin: 'Koti', eng: 'Home' },
    navigationLogin: { fin: 'Kirjaudu sisään', eng: 'Login' },
    navigationRegister: { fin: 'Rekisteröidy', eng: 'Register' },
    navigationLogOut: { fin: 'Kirjaudu ulos', eng: 'Logout' },
    navigationProfile: { fin: 'Profiili', eng: 'Profile' },
    formButton: { fin: 'Kysely', eng: 'Form' },
    loginButton: { fin: 'Kirjaudu', eng: 'Login' },
    loginHolder: { fin: 'Olet onnistuneesti kirjautunut sisään!', eng: 'You have succesfully logged in' },
    mainPageLink: { fin: 'Takaisin etusivulle', eng: 'Back to main page' },
    registerButton: { fin: 'Rekisteröidy', eng: 'Register' },
    emailPlaceHolder: { fin: 'Sähköpostiosoite', eng: 'Email' },
    passwordPlaceHolder: { fin: 'Salasana', eng: 'Password' },
    passwordConfirmationPlaceHolder: { fin: 'Salasanan varmennus', eng: 'Password confirmation' },
    registrationError: { fin: 'Et voi rekisteröityä sellaisella sähköpostiosoitteella, jota ei ole lisätty tietokantaan kandidaattina!', eng: 'You cannot register an account for email address that does not exist as a candidate!' },
    passwordConfirmationError: { fin: 'Varmennetun salasanan täytyy täsmätä salasanan kanssa', eng: 'Confirmation password must match with password' },
    profileButton: { fin: 'Varmista tiedot', eng: 'Submit Information' },
    adminLogo: { fin: 'Ylläpitäjän paneli', eng: 'Admin Panel' },
    addCandidates: { fin: 'Lisää monta kandidaattia', eng: 'Add Candidates' },
    addCandidatesCautionHolder: { fin: 'Lisätään kandidaatit, jotka eivät ole tietokannassa', eng: 'This will add all the candidates, which are not present in the database' },
    addCandidate: { fin: 'Lisää yksi kandidaatti', eng: 'Add One Candidate' },
    browseCandidates: { fin: 'Selaa kandidaatteja', eng: 'Browse Candidates' },
    addQuestion: { fin: 'Lisää kysymys', eng: 'Add Question' },
    browseQuestions: { fin: 'Selaa kysymyksiä', eng: 'Browse Questions' },
    agreeButton: { fin: 'Samaa mieltä', eng: 'Agree' },
    disagreeButton: { fin: 'Eri mieltä', eng: 'Disagree' },
    fillFormButton: { fin: 'Lähetä', eng: 'Submit' },
    removeButton: { fin: 'Poista', eng: 'Remove' },
    browseButton: { fin: 'Selaa', eng: 'Browse file' },
    matchingCandidates: { fin: 'Saman näkemyksen omaavat kandit:', eng: 'Candidates with matching values:' },
    oneCandidate: { fin: 'Täytä alla olevat tiedot lisätäksesi yhden kandidaatin:', eng: 'Fill in the information below to add one candidate:' },
    manyCandidates: { fin: 'Voit lisätä useamman kandidaatin alla olevan linkin kautta. Vain CSV tiedostot käyvät. ', eng: 'You can add candidates by the link below. Only CSV files are acceptable.' },
    firstName: { fin: 'Etunimi:', eng: 'First name:' },
    surName: { fin: 'Sukunimi:', eng: 'Surname:' },
    school: { fin: 'Koulu:', eng: 'School:' },
    selectStudentAssociationList: { fin: 'Opiskelijakunta:', eng: 'Student Association:' },
    campus: { fin: 'Kampus:', eng: 'Campus:' },
    electoralDistrict: { fin: 'Vaalipiiri:', eng: 'Electoral District:' },
    electoralAlliance: { fin: 'Vaaliliitto:', eng: 'Electoral Alliance:' },
    description: { fin: 'Kuvaus:', eng: 'Description:' },
    filterCandidateLabel: { fin: 'Suodata koulun perusteella', eng: 'Filter by School' },
    addQuestionButton: { fin: 'Lisää kysymys', eng: 'Add question' },
    deleteButton: { fin: 'Poista', eng: 'Delete' },
    editButton: { fin: 'Muokkaa', eng: 'Edit' },
    updateButton: { fin: 'Päivitä tiedot', eng: 'Update your information' },
    formLink: { fin: 'Linkki täytettyyn kyselyyn', eng: 'Link to your filled form' },
    uploadPicture: { fin: 'Lataa profiilikuva', eng: 'Upload a profile picture' },
    candidateHolder: { fin: 'Kandidaatti', eng: 'Candidate' },
    studentAssociationHolder: { fin: 'Opiskelijakunta', eng: 'Student Association' },
    deleteHolder: { fin: 'Poista', eng: 'Delete' },
    successQuestionAddedHolder: { fin: 'Olet onnistuneesti lisännyt uuden kysymyksen', eng: 'You have succesfully submitted a question"' },
    questionHolder: { fin: 'Kysymys:', eng: 'Question:' },
    continueHolder: { fin: 'Jatka', eng: 'Proceed' },
    wrongPasswordHolder: { fin: 'Väärä käyttäjätunnus tai salasana', eng: 'Invalid Username Or Password' },
    addedCandidatesToDatabaseAlert: { fin: 'Kanditaatit onnistuneesti lisätty tietokantaan', eng: 'Candidates have been added into the database' },
    addingOneCandidateToDatabaseAlert: { fin: 'Kandidaatti onnistuneesti lisätty tietokantaan', eng: 'Succesfully added user to database' },
    addingOneCandidateToDatabaseErrorAlert: { fin: 'Kandidaatti tällä sähköpostiosoitteella on jo olemassa', eng: 'Email with this address already exists as a user' },
    changeProfileDataAlert: { fin: 'Olet onnistuneesti päivittänyt profiilisi tiedot', eng: 'You have Succesfully updated your profile data' },
    filledFormAlert: { fin: 'Olet onnistuneesti täyttänyt kyselyn', eng: 'You have succesfully filled the form' },
    noSimilarCandidates: { fin: 'Valitettavasti kukaan ei ollut samaa mieltä kanssasi', eng: 'Unfortunately no one related with your answers' },
}

export default language;