const language = {
    title: { fin: 'Vaalikone', eng: 'VotingAid' },
    homePageDescription: { fin: 'Tervetuloa käyttämään vaalikonetta!', eng: 'Welcome to our voting aid application!' },
    selectStudentAssociation: { fin: 'Valitse opiskelijakuntasi', eng: 'Choose your student association' },
    navigationHome: { fin: 'Koti', eng: 'Home' },
    navigationLogin: { fin: 'Kirjaudu sisään', eng: 'Login' },
    navigationRegister: { fin: 'Rekisteröidy', eng: 'Register' },
    navigationLogOut: { fin: 'Kirjaudu ulos', eng: 'Logout' },
    navigationProfile: { fin: 'Profiili', eng: 'Profile' },
    formButton: { fin: 'Kysely', eng: 'Form' },
    loginButton: { fin: 'Kirjaudu', eng: 'Login' },
    mainPageLink: { fin: 'Takaisin etusivulle', eng: 'Back to main page' },
    registerButton: { fin: 'Rekisteröidy', eng: 'Register' },
    emailPlaceHolder: { fin: 'Sähköpostiosoite', eng: 'Email' },
    passwordPlaceHolder: { fin: 'Salasana', eng: 'Password' },
    passwordConfirmationPlaceHolder: { fin: 'Salasanan varmennus', eng: 'Password confirmation' },
    profileButton: { fin: 'Varmista tiedot', eng: 'Submit Information' },
    adminLogo: { fin: 'Ylläpitäjän paneli', eng: 'Admin Panel' },
    addCandidates: { fin: 'Lisää monta kandidaattia', eng: 'Add Candidates' },
    addCandidate: { fin: 'Lisää yksi kandidaatti', eng: 'Add One Candidate' },
    browseCandidates: { fin: 'Selaa kandidaatteja', eng: 'Browse Candidates' },
    addQuestion: { fin: 'Lisää kysymys', eng: 'Add Question' },
    browseQuestions: { fin: 'Selaa kysymyksiä', eng: 'Browse Questions' },
    agreeButton: { fin: 'Samaa mieltä', eng: 'Agree' },
    disagreeButton: { fin: 'Eri mieltä', eng: 'Disagree' },
    fillFormButton: { fin: 'Lähetä', eng: 'Submit' },
    removeButton: { fin: 'Poista', eng: 'Remove' },
    browseButton: { fin: 'Selaa', eng: 'Browse file' },
    matchingCandidates: { fin: 'Saman näkemyksen omaavat kandit:', eng: 'Candidates with matching values:' },
    oneCandidate: { fin: 'Täytä alla olevat tiedot lisätäksesi yhden kandidaatin:', eng: 'Fill in the information below to add one candidate:' },
    manyCandidates: { fin: 'Voit lisätä useamman kandidaatin alla olevan linkin kautta. Vain CSV tiedostot käyvät. ', eng: 'You can add candidates by the link below. Only CSV files are acceptable.' },
    firstName: { fin: 'Etunimi:', eng: 'First name:' },
    surName: { fin: 'Sukunimi:', eng: 'Surname:' },
    school: { fin: 'Koulu:', eng: 'School:' },
    selectStudentAssociation: { fin: 'Opiskelijakunta:', eng: 'Student Association:' },
    campus: { fin: 'Kampus:', eng: 'Campus:' },
    electoralDistrict: { fin: 'Vaalipiiri:', eng: 'Electoral District:' },
    electoralAlliance: { fin: 'Vaaliliitto:', eng: 'Electoral Alliance:' },
    description: { fin: 'Kuvaus:', eng: 'Description:' },
    filterCandidateLabel: { fin: 'Suodata koulun perusteella', eng: 'Filter by School' },
    addQuestionButton: { fin: 'Lisää kysymys', eng: 'Add question' },
    deleteButton: { fin: 'Poista', eng: 'Delete' },
    editButton: { fin: 'Muokkaa', eng: 'Edit' },
    updateButton: { fin: 'Päivitä tiedot', eng: 'Update your information' },
    formLink: { fin: 'Linkki täytettyyn kyselyyn', eng: 'Link to your filled form' },
    uploadPicture: { fin: 'Lataa profiilikuva', eng: 'Upload a profile picture' },
    candidateHolder: { fin: 'Kandidaatti', eng: 'Candidate' },
    studentAssociationHolder: { fin: 'Opiskelijakunta', eng: 'Student Association' },
    deleteHolder: { fin: 'Poista', eng: 'Delete' },
}

export default language;